name = "QuantumTrails"
uuid = "9812b7d4-376f-42e6-9e83-70a54ac4d71f"
keywords = ["quantum walks", "probabilistic models", "simulation", "web application"]
license = "MIT"
authors = ["Luis M. B. Varona <lbvarona@mta.ca>"]
description = "An interactive web-based simulator of Fourier quantum walks, powered by Genie.jl."
maintainers = ["Luis M. B. Varona <lbvarona@mta.ca>"]
readme = "README.md"
repository = "https://github.com/Luis-Varona/QuantumTrails"
version = "0.1.0-dev"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CairoMakie = ">=0.12, <1.0"
Genie = "5.24"
LinearAlgebra = "1.10"
Random = "1.10"
SparseArrays = "1.10"
julia = "1.10"

[extras]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
